
export const TEMPLATE_COMMUNITY_DETAILS_REQUEST = "TEMPLATE_COMMUNITY_DETAILS_REQUEST";
export const TEMPLATE_COMMUNITY_DETAILS_SUCCESS = "TEMPLATE_COMMUNITY_DETAILS_SUCCESS";
export const TEMPLATE_COMMUNITY_DETAILS_FAIL = "TEMPLATE_COMMUNITY_DETAILS_FAIL";
