export const ROLE_AND_PERMISSIONS_REQUEST = "ROLE_AND_PERMISSIONS_REQUEST";
export const ROLE_AND_PERMISSIONS_SUCCESS = "ROLE_AND_PERMISSIONS_SUCCESS";
export const ROLE_AND_PERMISSIONS_FAIL = "ROLE_AND_PERMISSIONS_FAIL";